apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxp-prediction
  namespace: fxp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fxp-prediction
  template:
    metadata:
      labels:
        app: fxp-prediction
    spec:
      containers:
      - name: fxp-prediction
        image: tarek111778/fxp-prediction-image:v1
        ports:
        - containerPort: 5002
        env:
        - name: DATA_STORAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fxp-config
              key: DATA_STORAGE_SERVICE_URL