apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxp-gateway
  namespace: fxp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fxp-gateway
  template:
    metadata:
      labels:
        app: fxp-gateway
    spec:
      containers:
      - name: fxp-gateway
        image: tarek111778/fxp-gateway-image:v1
        ports:
        - containerPort: 5001
        env:
        - name: PREDICTION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fxp-config
              key: PREDICTION_SERVICE_URL
        - name: DATA_STORAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fxp-config
              key: DATA_STORAGE_SERVICE_URL
